### ISSUE TITLE
Getting this error when running first setup script 

### ISSUE THREAD

**Issue by nogueiradouglas** [MMAmeta/MMAmeta#2]
Hi there, I'm very new to github and python. I followed all prior instructions but am getting stuck [here ](https://github.com/metaMMA/metaMMA/wiki/Windows#step-5-run-the-set-up-scripts)with the following error message.

```
C:\Users\Doug\metaMMA>py -3 setup.py
Traceback (most recent call last):
  File "C:\Users\Doug\metaMMA\plex_token.py", line 6, in <module>
    base64string = base64.encodestring(('%s:%s' % (user_info.plex_username, user_info.plex_password)).encode()).decode().replace('\n', '')
AttributeError: module 'base64' has no attribute 'encodestring'
Traceback (most recent call last):
  File "C:\Users\Doug\metaMMA\setup.py", line 20, in <module>
    vdata = open(info_check.meta+'version.txt','r')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Doug\\.metaMMA\\version.txt'
```

Any help is appreciated!

**Comment by nogueiradouglas** [comment]
It seems that this is an issue with the version of python that I am running. (Currently 3.10.0) Do you happen to know which version you used to make this work?
